stages:
  - lint
  - build
  - scan

variables:
  TF_VER: "1.7.5"
  ANSIBLE_VER: "2.16.5"
  K8S_VER: "1.29.2"
  HADOLINT_VER: "2.12.0-debian"

.lint_template:
  stage: lint
  image: hadolint/hadolint:v$HADOLINT_VER
  tags:
    - cluster-runner
  script:
    - hadolint $DOCKERFILE
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
      changes:
        - $DOCKERFILE
    - if: $CI_PIPELINE_SOURCE == "web"

lint-terraform:
  extends: .lint_template
  stage: lint
  variables:
    DOCKERFILE: "images/terraform/Dockerfile.tf-runner"

lint-k8s:
  extends: .lint_template
  stage: lint
  variables:
    DOCKERFILE: "images/k8s/Dockerfile.k8s-deployer"

lint-ansible:
  extends: .lint_template
  stage: lint
  variables:
    DOCKERFILE: "images/ansible/Dockerfile.ansible-runner"

# Use Kaniko debug version with shell because GitLab runner can not run commands in containers without shell
.build_template:
  stage: build
  tags:
    - cluster-runner
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_PIPELINE_SOURCE == "web"
    - if: $CI_PIPELINE_SOURCE == "push"
      changes:
        - images/**/*
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  before_script:
    - mkdir -p /kaniko/.docker
    # Kaniko uses configuration file for auth in registry
    - echo "{\"auths\":{\"$IMAGE_REGISTRY\":{\"auth\":\"$(printf "%s:%s" "$REPO_USER" "$REPO_PASSWORD" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json

# Build Terraform runner image for main CI/CD pipeline in k8s-infrastructure repository
build-terraform:
  extends: .build_template
  needs: ["lint-terraform"]
  script:
    - >
      /kaniko/executor
      --context $CI_PROJECT_DIR
      --dockerfile $CI_PROJECT_DIR/images/terraform/Dockerfile.tf-runner
      --target tf-stage
      --build-arg TF_VER=$TF_VERSION
      --destination $REGISTRY_PATH/tf-runner:latest
      --destination $REGISTRY_PATH/tf-runner:$TF_VERSION
      --destination $REGISTRY_PATH/tf-runner:$CI_COMMIT_SHORT_SHA
      --cache=true
      --cache-repo=$REGISTRY_PATH/tf-cache

# Build Ansible runner image for main CI/CD pipeline in k8s-infrastructure repository
build-ansible:
  extends: .build_template
  needs: ["lint-ansible"]
  script:
    - >
      /kaniko/executor
      --context $CI_PROJECT_DIR/images/ansible
      --dockerfile $CI_PROJECT_DIR/images/ansible/Dockerfile.ansible-runner
      --build-arg ANSIBLE_VER=$ANSIBLE_VERSION
      --destination $REGISTRY_PATH/ansible-runner:latest
      --destination $REGISTRY_PATH/ansible-runner:$ANSIBLE_VERSION
      --destination $REGISTRY_PATH/ansible-runner:$CI_COMMIT_SHORT_SHA
      --cache=true
      --cache-repo=$REGISTRY_PATH/ansible-cache

# Build K8s runner image for main CI/CD pipeline in k8s-infrastructure repository
build-k8s:
  extends: .build_template
  needs: ["lint-k8s"]
  script:
    - >
      /kaniko/executor
      --context $CI_PROJECT_DIR
      --dockerfile $CI_PROJECT_DIR/images/k8s/Dockerfile.k8s-deployer
      --target k8s-stage
      --build-arg K8S_VER=$K8S_VERSION
      --destination $REGISTRY_PATH/k8s-deployer:latest
      --destination $REGISTRY_PATH/k8s-deployer:$K8S_VERSION
      --destination $REGISTRY_PATH/k8s-deployer:$CI_COMMIT_SHORT_SHA
      --cache=true
      --cache-repo=$REGISTRY_PATH/k8s-cache


security-scan:
  stage: scan
  image: 
    name: aquasec/trivy:latest
    entrypoint: [""]
  tags:
    - cluster-runner
  variables:
    # Cache Trivy dependencies base (~ 200 MB) to speed up scanning
    TRIVY_CACHE_DIR: ".trivycache/"
  cache:
    paths:
      - .trivycache/
  parallel:
    matrix:
      - IMAGE_NAME: ["tf-runner", "ansible-runner", "k8s-deployer"]
  script:
    - echo "Scanning image $REGISTRY_PATH/$IMAGE_NAME:latest"
    # 1. Generate detailed report in JSON format for GitLab
    - >
      trivy image --format template --template "@/contrib/gitlab.tpl" 
      --output gl-container-scanning-report.json 
      $REGISTRY_PATH/$IMAGE_NAME:latest
    # 2. Output a brief summary to the pipeline console (for the eyes)
    - trivy image --severity HIGH,CRITICAL $REGISTRY_PATH/$IMAGE_NAME:latest
  artifacts:
    reports:
      container_scanning: gl-container-scanning-report-$IMAGE_NAME.json
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_PIPELINE_SOURCE == "web"
    - if: $CI_PIPELINE_SOURCE == "push"
      changes:
        - images/**/*
