stages:
  - lint
  - build
  - scan
  - update-infra-tools

variables:
  TF_VER: "1.7.5"
  ANSIBLE_VER: "2.16.5"
  K8S_VER: "1.29.2"
  HADOLINT_VER: "2.12.0-debian"
  TRIVY_VER: "0.49.1"

# Rules template for stage trigger
.base_rules:
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_PIPELINE_SOURCE == "push"
      changes:
        - images/$COMPONENT/**/*
    - if: $CI_PIPELINE_SOURCE == "web"

# Common template for all lint stages
.lint_template:
  stage: lint
  image: hadolint/hadolint:v$HADOLINT_VER
  tags:
    - cluster-runner
  script:
    - hadolint $DOCKERFILE

lint-terraform:
  extends: [.lint_template, .base_rules]
  variables:
    COMPONENT: "terraform"
    DOCKERFILE: "images/terraform/Dockerfile.tf-runner"

lint-k8s:
  extends: [.lint_template, .base_rules]
  variables:
    COMPONENT: "k8s"
    DOCKERFILE: "images/k8s/Dockerfile.k8s-deployer"

lint-ansible:
  extends: [.lint_template, .base_rules]
  variables:
    COMPONENT: "ansible"
    DOCKERFILE: "images/ansible/Dockerfile.ansible-runner"

# Use Kaniko debug version with shell because GitLab runner can not run commands in containers without shell
.build_template:
  stage: build
  tags:
    - cluster-runner
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  before_script:
    - mkdir -p /kaniko/.docker
    # Kaniko uses configuration file for auth in registry
    - echo "{\"auths\":{\"$IMAGE_REGISTRY\":{\"auth\":\"$(printf "%s:%s" "$REPO_USER" "$REPO_PASSWORD" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json

# Build Terraform runner image for main CI/CD pipeline in k8s-infrastructure repository
build-terraform:
  extends: [.build_template, .base_rules]
  needs: ["lint-terraform"]
  variables:
    COMPONENT: "terraform"
  script:
    - >
      /kaniko/executor
      --context $CI_PROJECT_DIR
      --dockerfile $CI_PROJECT_DIR/images/terraform/Dockerfile.tf-runner
      --build-arg TF_VER=$TF_VER
      --destination $REGISTRY_PATH/tf-runner:latest
      --destination $REGISTRY_PATH/tf-runner:$TF_VER
      --destination $REGISTRY_PATH/tf-runner:$CI_COMMIT_SHORT_SHA
      --cache=true
      --cache-repo=$REGISTRY_PATH/tf-cache

# Build Ansible runner image for main CI/CD pipeline in k8s-infrastructure repository
build-ansible:
  extends: [.build_template, .base_rules]
  needs: ["lint-ansible"]
  variables:
    COMPONENT: "ansible"
  script:
    - >
      /kaniko/executor
      --context $CI_PROJECT_DIR/images/ansible
      --dockerfile $CI_PROJECT_DIR/images/ansible/Dockerfile.ansible-runner
      --build-arg ANSIBLE_VER=$ANSIBLE_VER
      --destination $REGISTRY_PATH/ansible-runner:latest
      --destination $REGISTRY_PATH/ansible-runner:$ANSIBLE_VER
      --destination $REGISTRY_PATH/ansible-runner:$CI_COMMIT_SHORT_SHA
      --cache=true
      --cache-repo=$REGISTRY_PATH/ansible-cache

# Build K8s runner image for main CI/CD pipeline in k8s-infrastructure repository
build-k8s:
  extends: [.build_template, .base_rules]
  needs: ["lint-k8s"]
  variables:
    COMPONENT: "k8s"
  script:
    - >
      /kaniko/executor
      --context $CI_PROJECT_DIR
      --dockerfile $CI_PROJECT_DIR/images/k8s/Dockerfile.k8s-deployer
      --build-arg K8S_VER=$K8S_VER
      --destination $REGISTRY_PATH/k8s-deployer:latest
      --destination $REGISTRY_PATH/k8s-deployer:$K8S_VER
      --destination $REGISTRY_PATH/k8s-deployer:$CI_COMMIT_SHORT_SHA
      --cache=true
      --cache-repo=$REGISTRY_PATH/k8s-cache


.scan_template:
  stage: scan
  image: 
    name: aquasec/trivy:${TRIVY_VER}
    entrypoint: [""]
  tags:
    - cluster-runner
  variables:
    # Cache Trivy dependencies base (~ 200 MB) to speed up scanning
    TRIVY_CACHE_DIR: ".trivycache/"
  cache:
    paths:
      - .trivycache/
  script:
    - echo "Scanning image $REGISTRY_PATH/$IMAGE_NAME:latest"
    # 1. Generate detailed report in JSON format for GitLab
    - >
      trivy image --format template --template "@/contrib/gitlab.tpl" 
      --output "gl-container-scanning-report-$IMAGE_NAME.json" 
      $REGISTRY_PATH/$IMAGE_NAME:latest
    # 2. Output a brief summary to the pipeline console (for the eyes)
    - trivy image --severity HIGH,CRITICAL "$REGISTRY_PATH/$IMAGE_NAME:latest"
  artifacts:
    reports:
      container_scanning: "gl-container-scanning-report-$IMAGE_NAME.json"

scan-terraform:
  extends: [.scan_template, .base_rules]
  variables: 
    IMAGE_NAME: "tf-runner"
    COMPONENT: "terraform"
  needs: ["build-terraform"]

scan-ansible:
  extends: [.scan_template, .base_rules]
  variables: 
    IMAGE_NAME: "ansible-runner"
    COMPONENT: "ansible"
  needs: ["build-ansible"]

scan-k8s:
  extends: [.scan_template, .base_rules]
  variables: 
    IMAGE_NAME: "k8s-deployer"
    COMPONENT: "k8s"
  needs: ["build-k8s"]


.update_template:
  stage: update-infra-tools
  image: alpine:3.19
  before_script:
    - apk add --no-cache git curl
    - git config --global user.email "${GITLAB_USER_EMAIL}"
    - git config --global user.name "${GITLAB_USER_NAME} (CI/CD Bot)"
  script:
    # 1. Clone infrastructure repository
    - git clone https://oauth2:${INFRA_REPO_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_NAMESPACE}/k8s-infrastructure.git
    - cd k8s-infrastructure
    # 2. Change tool version in file
    - sed -i "s/${VAR_NAME}=.*/${VAR_NAME}=${NEW_VERSION}/" versions.env
    # 3. Push changes
    - git add versions.env
    - |
      if git diff --cached --quiet; then
        echo "No changes to commit"
      else
        git commit -m "Update ${VAR_NAME} to ${NEW_VERSION} [skip ci]"
        git push origin main
      fi
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

update-tf-version:
  extends: [.update_template, .base_rules]
  needs: ["scan-terraform"]
  variables:
    COMPONENT: "terraform"
    VAR_NAME: "TF_RUNNER_VER"
    NEW_VERSION: "$CI_COMMIT_SHORT_SHA"

update-ansible-version:
  extends: [.update_template, .base_rules]
  needs: ["scan-ansible"]
  variables:
    COMPONENT: "ansible"
    VAR_NAME: "ANSIBLE_RUNNER_VER"
    NEW_VERSION: "$CI_COMMIT_SHORT_SHA"

update-k8s-version:
  extends: [.update_template, .base_rules]
  needs: ["scan-k8s"]
  variables:
    COMPONENT: "k8s"
    VAR_NAME: "K8S_DEPLOYER_VER"
    NEW_VERSION: "$CI_COMMIT_SHORT_SHA"
