stages:
  - build
  - scan

variables:
  TF_VERSION: "1.7.5"
  ANSIBLE_VERSION: "2.16.5"
  K8S_VERSION: "1.29.2"
  REGISTRY_PATH: $CI_REGISTRY_IMAGE

# Use debug version with shell because GitLab runner can not run commands without shell
.kaniko_build_template:
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  before_script:
    # Kaniko uses configuration file for auth in registry
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(printf "%s:%s" "$CI_REGISTRY_USER" "$CI_REGISTRY_PASSWORD" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json

build-terraform-kaniko:
  extends: .kaniko_build_template
  stage: build
  script:
    - /kaniko/executor \
      --context $CI_PROJECT_DIR \
      --dockerfile $CI_PROJECT_DIR/Dockerfile \
      --target tf-stage \
      --build-arg TF_VER=$TF_VERSION \
      --destination $REGISTRY_PATH/tf-runner:latest \
      --destination $REGISTRY_PATH/tf-runner:$TF_VERSION \
      --destination $REGISTRY_PATH/tf-runner:$CI_COMMIT_SHORT_SHA \
      --cache=true \
      --cache-repo=$REGISTRY_PATH/tf-cache
  rules:
    - changes:
        - images/terraform/**/*
    - if: $CI_PIPELINE_SOURCE == "schedule"

build-ansible:
  extends: .build_template
  stage: build
  script:
    - docker build -t $CI_REGISTRY_IMAGE/ansible:latest ./images/ansible
    - docker push $CI_REGISTRY_IMAGE/ansible:latest
  rules:
    - changes:
        - images/ansible/**/*

build-k8s:
  extends: .build_template
  stage: build
  script:
    - |
      docker build \
        --target k8s-stage \
        --build-arg K8S_VER=$K8S_VERSION \
        -t $REGISTRY_PATH/k8s-deployer:latest \
        -t $REGISTRY_PATH/k8s-deployer:$K8S_VERSION \
        -t $REGISTRY_PATH/k8s-deployer:$CI_COMMIT_SHORT_SHA .
    - docker push $REGISTRY_PATH/k8s-deployer --all-tags
  rules:
    - changes:
        - images/k8s/**/*
    - if: $CI_PIPELINE_SOURCE == "schedule"

security-scan:
  stage: scan
  image: 
    name: aquasec/trivy:latest
    entrypoint: [""]
  script:
    - trivy image --exit-code 1 --severity HIGH,CRITICAL $REGISTRY_PATH/tf-runner:latest
    - trivy image --exit-code 1 --severity HIGH,CRITICAL $REGISTRY_PATH/k8s-deployer:latest
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"

